"""added unique=True for short field

Revision ID: 9acd216e88ec
Revises: 
Create Date: 2024-01-12 10:02:18.678819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acd216e88ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'url_map', ['short'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_map', type_='unique')
    # ### end Alembic commands ###
